services:
  spring-state-population:
    image: 'spring-boot-state-population'
    build:
      context: .
    container_name: spring-state-population
    depends_on:
      state-population-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://state-population-db:5432/state-population
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8000:8080"

  state-population-db:
    image: 'postgres:17-alpine'
    container_name: state-population-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=state-population
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - "5432:5432"